# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
        env:
          - NODE_ENV=test
          - PGDATABASE=test
          - PGUSER=postgres

      - image: mdillon/postgis:9.6-alpine
        env:
          - POSTGRES_DB=test
          - POSTGRES_USER=postgres

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn lint
      - run: yarn flow:check
      - run: yarn db:migrate
      - run: yarn test
      # - run: yarn flow:coverage
